Feature/sentry
Amsterdam/vergunningcheck pull request #210
Opened 2020-06-30 14:08 UTC by svenjens

2020-07-02 08:58 UTC, robinpiets requested changes

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/components/Visual.js
> +import * as Sentry from "@sentry/browser";
Can you not only import `captureException` instead of `*`?

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/components/Visual.js
> +    Sentry.captureException(`${src} niet gevonden`);
Shall we do English errors?

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/index.js
> +
Can you change this to `Sentry.init(sentryConfig);` and move the config to a new folder `config/sentry.ts`? 

Let's make a new ticket to move MatomoConfig and the app config there as well

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/pages/LocationPage.js
> +import { Heading, Paragraph } from "@datapunt/asc-ui";
Please do not add files that havent changed. Very confusing

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/pages/LocationPage.test.js
> +import { createMemoryHistory } from "history";
Nothing changed here right?

2020-07-02 08:58 UTC, robinpiets commented on apps/client/src/intros/KozijnenIntroSTTR/index.js
> +import React from "react";
Nothing changed here right?

2020-07-02 08:58 UTC, robinpiets commented on ci/nginx-deployed.conf
> +        add_header Content-Security-Policy "default-src 'self'; script-src 'unsafe-inline' 'self' https://sentry.data.amsterdam.nl/ https://analytics.data.amsterdam.nl https://w.usabilla.com https://
👍

2020-07-07 15:46 UTC, afjlambert approved these changes

2020-07-07 19:00 UTC, robinpiets approved these changes
Please "squash and merge" and rename commit

2020-07-07 19:00 UTC, robinpiets commented on apps/client/src/components/Visual.js
> +  const setError = () => {
np: let's rename to `handleError`

2020-07-09 07:35 UTC, merged