Question wrapper for chappie 2.0
Amsterdam/vergunningcheck pull request #225
Opened 2020-07-07 07:01 UTC by svenjens

2020-07-16 10:39 UTC, svenjens commented
Can be checked here. 
https://feature-question-wrapper-base.chappie2.com/test

2020-07-20 13:20 UTC, robinpiets requested changes

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/checker/components/Question.js
> +import React, { useEffect } from "react";
We're going to prevent duplicate code so you can replace the original Question.js

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/checker/components/Question.js
> +                  }) => {
Indentation is odd here

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/components/DebugDecisionTable.js
> +export default ({ checker, slug }) => {
`DebugDecisionTable.js` on `develop` has this: `export default ({ checker, topic }) => {`
So I think this change can be undone?

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/components/Question.js
> +                  }) => {
Indentation if odd

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/components/Question.js
> +export default Question;
Weird no newline

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +        // go go go
Odd comment

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +      }
This `else` can be removed

2020-07-20 13:20 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +    }
This else can be removed, right? The logic will be higher up the tree?

2020-07-20 15:04 UTC, robinpiets approved these changes

2020-07-20 15:04 UTC, merged