Feature: Added full-width background to Stepper
Amsterdam/vergunningcheck pull request #332
Opened 2020-07-28 15:49 UTC by robinpiets

2020-07-28 16:57 UTC, svenjens commented
Is the margin correct? On the bottom seems to be much more space

2020-07-28 16:58 UTC, svenjens reviewed
There seems to be more space at the bottom than on the top

2020-07-29 07:02 UTC, afjlambert requested changes

2020-07-29 07:02 UTC, afjlambert commented on apps/client/src/routes.js
> +  },
Did you add this intentionally?

2020-07-29 08:06 UTC, robinpiets commented on apps/client/src/routes.js
> +  },
Nope. By accident. Removing it now

2020-07-29 08:10 UTC, robinpiets commented
> There seems to be more space at the bottom than on the top

The spacing had to do with the Nav component. You are free to place as much space as required.

This is the default:

![image](https://user-images.githubusercontent.com/7781865/88774443-bffa6300-d183-11ea-9ca1-e42a47b2209e.png)

2020-07-29 11:20 UTC, svenjens approved these changes

2020-07-29 11:21 UTC, merged