Feature/refactor stepper logic
Amsterdam/vergunningcheck pull request #333
Opened 2020-07-29 12:59 UTC by svenjens

2020-07-29 13:15 UTC, afjlambert requested changes

2020-07-29 13:15 UTC, afjlambert commented on apps/client/src/pages/WrapperPage.js
> +          checked={() => isFinished('location', 'address')}
I don't think this could actually work. `isFinished` uses `Array.includes` on the first argument only. You're passing two.

2020-07-29 13:15 UTC, afjlambert commented on apps/client/src/pages/WrapperPage.js
> +        >{console.log('isActive', isActive('location'))}
remove `console.log`?

2020-08-04 14:46 UTC, robinpiets requested changes

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Address.js
> +import { Paragraph } from "@datapunt/asc-ui";
I would like to rename the file `Address` to `LocationInput` and `Location` to `LocationResult`. Address is just too general. This also means renaming `setActiveState("address")` to `setActiveState("locationResult")`.

What do you think?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Address.js
> +      <Paragraph gutterBottom={useSTTR && topic.text?.addressPage ? null : 0}>
Something went wrong in merging with the chappie2.0 branch, because this whole text has changed:

On chappie2.0 branch:
```
<Paragraph gutterBottom={useSTTR ? null : 0}>
  {/* OLO Flow text */}
  {!useSTTR &&
    ` U hebt deze informatie nodig om de vergunningcheck te doen op
    het Omgevingsloket.`}
</Paragraph>
```

Please check carefully what text to place in this file

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Address.js
> +      )}
Something went wrong in merging with the chappie2.0 branch, because this whole text has been removed. Please check carefully what text to place in this file

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Address.js
> +  };
Shall we move this to config/index.ts? We can do this in a separate PR, I am adding this to the ToDo list.

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Address.js
> +    // Form is validated, we can proceed
This comment is in the wrong place

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Location/Location.js
> +        setActiveState("address");
There is still `finishedLocation: false` in withTopic.js

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +      // Go to "Conclusion"
These three lines can be removed and can be replaced with the comment: `// Go directly to "Contact Conclusion" and skip other questions`

We don't need the checker.previous() anymore

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +        setFinishedState(["questions", "conclusion"], true);
This should not enable the conclusion right? Why should this be here?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +    setFinishedState(["conclusion", "questions"], false);
Shall we wrap this in an `if (isFinished("conclusion"))...`?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/IntroPage.js
> -    ]);
Do we not need some sort of reset here?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  const { activeComponents, finishedComponents } = sessionContext[slug] || []; // At startup we don't have activeComponent or finishedComponents, so start with empty array.
Can you place the comment above?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  // Pass a component name, or a array of components, this array or component will all be finished or removed.
What do you mean with `will all be finished or removed.`?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +    // Save the new sessionData to the contex
contex -> context

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  };
If it's basically the same code than we can better use just one, or maybe something like this: ` const isFinished = (value) => isActive(value)`

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +                !isFinished("address")
Holy moly, this is a huge condition. Can we not just use `!isFinished("address")`?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +              {(!activeComponents || isActive("location")) && (
Can we not set an active component on first init `if (!activeComponents) ...`?

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +                  setFinishedState={setFinishedState}
you can shorten this to 
```
{...{
topic, 
isFinished, 
setActiveState,
setFinishedState,
}}
```

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +                checker={checker}
you can shorten this

2020-08-04 14:46 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +        )}
This part can be shortened

2020-08-04 14:53 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  // Pass a component name, or a array of components, this array or component will all be finished or removed.
Please enhance the second parameter

2020-08-04 14:59 UTC, robinpiets commented on apps/client/src/pages/IntroPage.js
> -    ]);
something like `setActive("locationInput")` here?

2020-08-05 13:12 UTC, robinpiets requested changes
It's becoming a very nice refactor!! I've got some minor points though

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/components/Location/LocationResult.js
> +    <Form onSubmit={onSubmit} data-testid={ADDRESS_PAGE}>
Can you rename `ADDRESS_PAGE` to `LOCATION_RESULT`?

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/components/Location/LocationResult.js
> +        {!useSTTR &&
As discussed...

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  const { activeComponents, finishedComponents } = sessionContext[slug];
The end of the comment `so start with empty array.` doesn't make sense anymore?

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +   * @param { Object[] | string } component - name of names of the components
Nice!

Only it's `name or names` instead of `name of names`

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +    let newFinishedComponents = finishedComponents; // If there are no finishedComponents start with a empty array.
Comment makes no sense anymore: `// If there are no finishedComponents start with a empty array.`

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  };
You can refactor this whole part to something like this:

```
// Comment
const allComponents = Array.isArray(component) ? component : [component];

// Comment
const newFinishedComponents =
  typeof value === "boolean" && value === false
    ? finishedComponents?.filter((c) => !allComponents.includes(c)) || []
    : [...finishedComponents, ...allComponents];

// Comment
sessionContext.setSessionData([slug, ...newFinishedComponents]);
```

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +  const isFinished = (component) => isActive(component, true);
Cool!

2020-08-05 13:12 UTC, robinpiets commented on apps/client/src/pages/WrapperPage.js
> +              {(!activeComponents || isActive("locationInput")) && (
You didn't find a way to init an activeComponent so we can drop the `!activeComponents` ?

2020-08-05 15:12 UTC, robinpiets approved these changes

2020-08-05 15:14 UTC, merged