Bug: fixed issue with undefined string
Amsterdam/vergunningcheck pull request #395
Opened 2020-08-13 13:21 UTC by robinpiets

2020-08-14 10:22 UTC, afjlambert requested changes
I don't think this improves the quality of our code. This is a util function an now does more then remove quotes.
If I pass `true` or `2` or `[]` this would still cause issues. To catch those inputs as well, this function would get more and more complicated.
Also, the function now returns `false` instead of a string. This makes the return signature different which could lead to other issues.
I would prefer converting this file to Typescript and making sure if you call removeQuotes it's actually a string.
Another solution would be calling this function like `removeQuotes(someVar || '')`.

2020-08-17 14:09 UTC, robinpiets commented
Good feedback @afjlambert! What if we make it like this:
```
export const removeQuotes = (str) => typeof str === "string" ? str.replace(/['"]+/g, "") : '';
```

2020-08-17 17:20 UTC, afjlambert approved these changes

2020-08-18 06:35 UTC, svenjens approved these changes

2020-08-18 07:39 UTC, merged