Chappie2 route redirects
Amsterdam/vergunningcheck pull request #411
Opened 2020-08-19 07:08 UTC by svenjens

Instead of creating a catch all. 
This pr takes care of handling to old routes and create a permanent redirect.

2020-08-19 13:57 UTC, afjlambert requested changes
We already have the concept of redirecting.

Why did you not add the following to `export const redirectConfig`? 
```
["/:slug/locatie", "/:slug"],
["/:slug/adresgegevens", "/:slug"],
["/:slug/vragen", "/:slug"],
["/:slug/uitkomsten", "/:slug"],
["/:slug/conclusie", "/:slug"],
```

I do like `{ from: "/:slug/conclusie", to: "/:slug" },` much better then the `['', '']` I introduced before.
What would be really great is `routes.ts` with `export const redirectConfig: { from: string, to: string } = ...`

2020-08-20 07:08 UTC, svenjens commented
> We already have the concept of redirecting.
> 
> Why did you not add the following to `export const redirectConfig` in `routes.js`?
> 
> ```
> ["/:slug/locatie", "/:slug"],
> ["/:slug/adresgegevens", "/:slug"],
> ["/:slug/vragen", "/:slug"],
> ["/:slug/uitkomsten", "/:slug"],
> ["/:slug/conclusie", "/:slug"],
> ```
> 
> I do like `{ from: "/:slug/conclusie", to: "/:slug" },` signature much better then the `['', '']` I introduced before.
> What would be really great is `routes.ts` with `export const redirectConfig: { from: string, to: string } = ...`.
> 
> And simply change:
> 
> ```
> {redirectConfig.map(([from, to]) => (
>   <Redirect key={from} {...{ from, to }} />
> ))}
> ```
> 
> to
> 
> ```
> {redirectConfig.map((config) => (
>   <Redirect key={from} {...config} />
> ))}
> ```

2020-08-20 10:43 UTC, robinpiets requested changes

2020-08-20 10:43 UTC, robinpiets commented on apps/client/src/components/Router.js
> +                return route.redirect.map((redirect, i) => (
Here you don't need the `i`

2020-08-20 10:43 UTC, robinpiets commented on apps/client/src/components/Router.js
> +            .map((route, i) => {
Can be refactored to (pseudo code):
```
 .map((route, i) => route.redirect ? route.redirect.map((redirect) => (<MyRedirect {...redirect} />) : <Route key={i} {...route} />)
```

2020-08-20 11:27 UTC, afjlambert commented
Can you validate if my last commit actually works?

2020-08-24 09:39 UTC, robinpiets approved these changes
LGTM!

.... conflicts 😢

2020-08-24 11:17 UTC, merged