Chappie 2.0
Amsterdam/vergunningcheck pull request #414
Opened 2020-08-19 12:50 UTC by robinpiets

2020-08-24 09:42 UTC, robinpiets commented on apps/client/src/components/AddressLine.js
> +export default ({ address: { streetName, houseNumberFull }, strong }) =>
Shall we move this to /atoms?

2020-08-26 10:19 UTC, afjlambert requested changes
Looks like a great improvement over chappie1.0!

Overall remarks, consider refactoring (roughly in this order):

1. Components in the different steps should not know about each other
2. We need way more tests
3. OLO flow should be separate page, using the same underlying components
4. dataNeeds is not implemented in the way it should

Please see inline comments for specific feedback.

I **do** approve this PR because work could continue on `develop`. Up to you guys.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/AddressLine.js
> +export default ({ address: { streetName, houseNumberFull }, strong }) =>
Good idea. Do we actually have a clear description of an `atom`?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Answers.js
> +                checked={userAnswer === answer.label}
Why has this been changed?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Layouts/BaseLayout.tsx
> +function BaseLayout({ children, checker, heading }: BaseLayoutProps) {
Now BaseLayout has access to checker. Not sure if this is a good idea. Maybe we can use a boolean instead. eg. `wideLayout=true` ?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Layouts/BaseLayoutStyles.js
> +    zoom: 0.7;
😆

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Nav.js
> +    if (onGoToNext) onGoToNext(e);
Nice improvement!

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Nav.js
> +    <NavStyle {...otherProps}>
Not sure if this is a good idea. Converting this to typescript later does not have desired result I think.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/RegisterLookupSummary.js
> +            setActiveState("locationInput");
Not sure if this component should handle this state change.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Router.js
> +            <Redirect key={redirect.from} {...redirect} />
👏

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
> +import { Icon, breakpoint, themeColor, themeSpacing } from "@datapunt/asc-ui";
Wow, big component. Can we split this up in smaller files?
Is this going to be part of asc-ui?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepTitle.tsx
> +  headingProps,
I do like this way of forwarding props to sub-component instead of de-structuring it here.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/ConclusionAlertStyles.ts
> +  /* @TODO: add yellow color to ASC-UI and replace it here */
Can you add a link to the asc-ui PR here?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakkapel plaatsen? Doe dan per dakkapel de vergunningcheck.",
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakraam plaatsen? Doe dan per dakraam de vergunningcheck.",
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>    addressPage?: string;
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
> +    sttrFile: "zonwering.json",
Do we want to release zonwering after chappie2.0? In that case we can maybe make this environment dependent. e.g use `isProduction`

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
> +    intro: "ZonweringRolluikIntro",
same here

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/hoc/withChecker.js
> +        <Component checker={checker} resetChecker={resetChecker} {...props} />
`checker.reset()` would be nice here. Will add it to my list of features for sttr-client@2.0

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/DevHomePage.js
> +      <p>Welcome to CHAPPIE 2.0</p>
👏

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/routes.js
>      ),
I think this route/config should be above the CheckerPage. That way the order is similar to the hierarchy of routes.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  if (!childrenProps) return null;
Why not move this to the top of the function?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  children: childrenProps,
`childrenProps` are the `children` right? Then that's a weird name because the props themselves are actually defined below.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  const { children } = usePassPropsToChildren(childrenProps, {
Please add a comment why we do this.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  if (!childrenProps) return null;
Why not move this to the top of the function?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakkapel plaatsen? Doe dan per dakkapel de vergunningcheck.",
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakraam plaatsen? Doe dan per dakraam de vergunningcheck.",
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/config/index.ts
>    addressPage?: string;
Please remove.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/utils/usePassPropsToChildren.ts
> +  childrenProps: React.ReactNode | boolean,
Weird name because they are not the props. Also; how can we accept a boolean here? We use `Children.map(boolean)` ??

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/utils/usePassPropsToChildren.ts
> +import React, { Children } from "react";
😕 this file...

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationInput.js
> +        // We don't go directly to Questions or Conclusion
Not sure what this comment implies.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationInput.js
> +        setActiveState("locationResult");
Not sure if this should be here, or in a component higher up the tree.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationInput.js
> +        setFinishedState(["locationResult", "questions", "conclusion"], false);
Location input should not manipulate state about question/conclusion imo.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationInput.js
> +        setActiveState("locationResult");
same here.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationResult.js
> +      if (typeof questionIndex !== "number") {
Why would `questionIndex` not be a number?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Location/LocationResult.js
> +  const address = sessionContext[topic.slug].address || {};
Not sure if this component should dig into the session itself or the parent should handle this logic.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Question.js
>  const Question = ({
These properties! Looks like a complex component.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/QuestionAnswer.tsx
> +  questionNeedsContactExit?: boolean;
why optional and no default value?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +  }, [setActiveState, setFinishedState]);
Can we move this logic to a parent component? Stepbystep maybe?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +  goToQuestion,
Why is the signature of this function `(string | number)` which is `"next"` or `"prev"` instead of just `(bool | number)`? Maybe still not ideal but a bit better.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +          // Go to the "Conclusion"
Not a useful comment. The name of the function is clear enough ;-)

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +      setFinishedState(["locationResult"], false);
This component should not know about location-stuff. Consider moving it up the component tree.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +  const onGoToQuestion = useCallback(
same here.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +        // @TODO: refactor this into isQuestionAnswered() because this code is used often
I'll add it to the list for sttr-client2.0

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +import React, { useCallback, useContext, useEffect, useState } from "react";
Whoah, this file is big. Can we split it up?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +  ]);
This is very error-prone imo.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +  const activeStyle = { marginTop: -1, borderColor: "white" };
As far as I know we never do it this way in the project.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +    if (isFinished("questions")) {
This if-statement can be removed I think. Just call `setFinishedState("questions", false)` ?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +        }
Can we move this block up to the top of this function?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/Questions.js
> +        if (!userAnswer || contactConclusion) return null;
Can we add `{}` around this return statement?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
> +  React.HTMLAttributes<HTMLDivElement>;
Please move this to the component itself, should not be part of the styles.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +  Props,
This is very weird imo.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +  ...otherProps
Can we not do de-structuring here? I'd prefer to name the actual props.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +  href,
Not clear to me why we need this `href`-prop.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +import { Checkmark } from "@datapunt/asc-assets";
Nice component.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +    return components.includes(...allComponents) || false;
If I'm not mistaken the `|| false` does nothing. `includes` returns true if true. If `includes` is false, then we return `false`

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +  const isActive = (component, finished = false) => {
`finished` prop seems weird here. Either rename or move the logic to `isFinished` ?

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +   * @param { int | ('next'|'prev') } value - This van be, 'next, prev or a int`
very weird signature imho.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +  };
We don't do styling this way in this project as far as I know.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +const CheckerPage = ({ checker, topic, resetChecker }) => {
I guess this would be the place to handle logic for setting the active / finished states of the step by step items.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +            done={isActive("locationInput") || isActive("locationResult")}
While reading this, I'm wondering... What does `done` actually do? I know active is the background color (and maybe related to scroll position) and `checked` is the chevron. `done` could be the blue line, but then it's value seems weird.

2020-08-26 10:19 UTC, afjlambert commented on apps/client/src/pages/CheckerPage.js
> +            style={
Inline style?

2020-08-26 10:20 UTC, afjlambert approved these changes

2020-08-26 10:25 UTC, afjlambert commented
I do see that our GitHub-bot said:
```
apps/client/build/static/js/15.js | +689 kB | +206 kB
apps/client/build/static/js/16.js | +146 kB | +46.8 kB
```
Maybe check if it's actually the case our bundle size increased by this much or that the bot is actually missing there are some big files removed too.

2020-08-26 12:43 UTC, afjlambert commented
Careful not to delete `chappie2.0` if you want to keep using the Netlify env.

2020-08-26 14:20 UTC, afjlambert commented on apps/client/src/routes.js
>      ),
consider also removing `exact: true` if it still works

2020-08-26 14:54 UTC, afjlambert commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +  href,
Because it'll be generic component used from asc-ui. We have the exception of using this on a single page app.

2020-08-27 07:48 UTC, robinpiets commented on apps/client/src/components/ConclusionAlertStyles.ts
> +  /* @TODO: add yellow color to ASC-UI and replace it here */
There has not been a PR yet, we need to wait for confirmation from the design-team

2020-08-27 08:05 UTC, robinpiets commented on apps/client/src/components/Layouts/BaseLayout.tsx
> +function BaseLayout({ children, checker, heading }: BaseLayoutProps) {
Fixed: https://github.com/Amsterdam/vergunningcheck/pull/440/commits/ad28042ec07d2f9309f676f7bb72680c2458b6eb

2020-08-27 08:06 UTC, robinpiets commented on apps/client/src/components/Location/LocationInput.js
> +        // We don't go directly to Questions or Conclusion
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/9a68632ad1c98f5ee87febf89b5e0ab2f97db6ac

2020-08-27 08:20 UTC, robinpiets commented on apps/client/src/components/Nav.js
> +    <NavStyle {...otherProps}>
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/c2eb858a0fc27875c7fd39a29145afce41001ab4

2020-08-27 08:32 UTC, robinpiets commented on apps/client/src/components/QuestionAnswer.tsx
> +  questionNeedsContactExit?: boolean;
as discussed

2020-08-27 08:32 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +  ]);
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/a625dacfd959550b35c4d8e6a6b55236535a8711

2020-08-27 08:32 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +        }
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/23f4520f6859f2d3253ccbb8de64c6c036fd948b

2020-08-27 08:35 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +        if (!userAnswer || contactConclusion) return null;
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/2e0c4f3b749fd99834667c8f3464dad546b220c5

2020-08-27 08:39 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepItem.tsx
> +  Props,
Since this is the way of working in ASC-UI I am going to keep it this way. But I understand your motivation and agree with you

2020-08-27 08:48 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  if (!childrenProps) return null;
duplicate comment

2020-08-27 08:52 UTC, robinpiets commented on apps/client/src/utils/usePassPropsToChildren.ts
> +  childrenProps: React.ReactNode | boolean,
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/09f243dc45dc286cdeb152193ba32d143645c4f4

2020-08-27 08:52 UTC, robinpiets commented on apps/client/src/utils/usePassPropsToChildren.ts
> +import React, { Children } from "react";
Hope this helps https://github.com/Amsterdam/vergunningcheck/pull/440/commits/09f243dc45dc286cdeb152193ba32d143645c4f4

2020-08-27 08:53 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  children: childrenProps,
Renamed to `childrenProp`
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/09f243dc45dc286cdeb152193ba32d143645c4f4

2020-08-27 08:53 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  const { children } = usePassPropsToChildren(childrenProps, {
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/09f243dc45dc286cdeb152193ba32d143645c4f4

2020-08-27 08:54 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepNavigation.tsx
> +  if (!childrenProps) return null;
React Hook "usePassPropsToChildren" must be called before this `return` statement

https://github.com/Amsterdam/vergunningcheck/pull/440/commits/09f243dc45dc286cdeb152193ba32d143645c4f4

2020-08-27 08:57 UTC, robinpiets commented on apps/client/src/config/index.ts
>    addressPage?: string;
Removed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/83abfcb6ad2ef1404ebad7f42ec203b21ed198f0

2020-08-27 08:57 UTC, robinpiets commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakkapel plaatsen? Doe dan per dakkapel de vergunningcheck.",
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/83abfcb6ad2ef1404ebad7f42ec203b21ed198f0

2020-08-27 08:57 UTC, robinpiets commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakkapel plaatsen? Doe dan per dakkapel de vergunningcheck.",
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/83abfcb6ad2ef1404ebad7f42ec203b21ed198f0

2020-08-27 08:57 UTC, robinpiets commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakraam plaatsen? Doe dan per dakraam de vergunningcheck.",
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/83abfcb6ad2ef1404ebad7f42ec203b21ed198f0

2020-08-27 08:57 UTC, robinpiets commented on apps/client/src/config/index.ts
>          "Gaat u meer dan 1 dakraam plaatsen? Doe dan per dakraam de vergunningcheck.",
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/83abfcb6ad2ef1404ebad7f42ec203b21ed198f0

2020-08-27 08:58 UTC, robinpiets commented on apps/client/src/config/index.ts
> +    sttrFile: "zonwering.json",
We're going to release with `zonwering`

2020-08-27 09:02 UTC, robinpiets commented on apps/client/src/pages/CheckerPage.js
> +    return components.includes(...allComponents) || false;
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/9ef3b688f8d7da688e3fc6ac7ffbd8059bf7110b

2020-08-27 09:10 UTC, robinpiets commented on apps/client/src/routes.js
>      ),
We can reorder this, but I tried removing the `exact: true` but this breaks the app. So I only switched the routes.
https://github.com/Amsterdam/vergunningcheck/pull/440/commits/70f5037e6e9b56271d54d4905dcee6164f542af7

2020-08-27 09:15 UTC, robinpiets commented on apps/client/src/components/Questions.js
> +          // Go to the "Conclusion"
Fixed https://github.com/Amsterdam/vergunningcheck/pull/440/commits/b711dc01073cfcd21d8b1deceef18518b5833348

2020-08-27 09:16 UTC, robinpiets commented on apps/client/src/components/StepByStepNavigation/StepByStepItemStyle.ts
> +  React.HTMLAttributes<HTMLDivElement>;
As discussed. I'm going to keep this since this is the way ASC-UI works. I still agree with you

2020-08-27 15:29 UTC, merged