RegisterLookupSummary now is TypeScript
Amsterdam/vergunningcheck pull request #581
Opened 2020-10-06 16:26 UTC by robinpiets

RegisterLookupSummary now is TypeScript

2020-10-06 18:18 UTC, svenjens approved these changes

2020-10-07 07:12 UTC, merged

2020-10-07 07:16 UTC, afjlambert requested changes

2020-10-07 07:16 UTC, afjlambert commented on apps/client/src/atoms/ComponentWrapper.ts
> +  marginBottom?: number | undefined;
Why did you do this? There's already a `?`.

2020-10-07 07:16 UTC, afjlambert commented on apps/client/src/components/RegisterLookupSummary.tsx
> +// @TODO: can you make a props file for these kinds of props, @andre?
Good question. Can you remove it from the source code however? I'll add it to the list of stuff to improve.

2020-10-07 07:16 UTC, afjlambert commented on apps/client/src/components/RegisterLookupSummary.tsx
> +  topic: any; // @TODO: replace with custom hooks
Replace it with IMTR-Client's `TopicType`

2020-10-07 07:16 UTC, afjlambert commented on apps/client/src/components/RegisterLookupSummary.tsx
> +    <ComponentWrapper marginBottom={hasIMTR && 0}>
👍 nice

2020-10-07 07:16 UTC, afjlambert commented on apps/client/src/components/RegisterLookupSummary.tsx
>    const { restrictions, zoningPlans } = address;
I believe if we type `Session` then address and zoningPlan's will all inherit their types.
Can you add a comment?
`// @TODO; type Session and/or Address and remove types of zoningPlan below`