Client outcomes enum
Amsterdam/vergunningcheck pull request #714
Opened 2020-11-25 13:58 UTC by robinpiets

This PR made `ClientOutcomes` way more robust by converting it to enum. Also, I've fixed the bug with the missing outcome text.

Please squash when approved.

Please make sure:
- [x] to add a label
- [x] to add one or more reviewers
- [x] you followed our checklist for [functional testing](https://github.com/Amsterdam/vergunningcheck/blob/master/TESTING.md)
- [x] you added the necessary documentation (either in the markdown files or inline)
- [x] you added the necessary automated tests

2020-11-25 14:06 UTC, svenjens approved these changes

2020-11-26 10:34 UTC, afjlambert requested changes

2020-11-26 10:34 UTC, afjlambert commented on packages/client/src/components/Questions.tsx
> +        const outcomeType = permitsPerQuestion[i] as ClientOutcomes;
Can you use : instead of as?

2020-11-26 12:36 UTC, afjlambert approved these changes

2020-11-26 12:40 UTC, merged