Add db poc
Amsterdam/vergunningcheck pull request #741
Opened 2020-12-17 11:37 UTC by afjlambert

Description 
- what does this feature or fix do?
- please explain (high level) how and why you implemented it this way

Please make sure:
- [ ] to add a label
- [ ] to add one or more reviewers
- [ ] you followed our checklist for [functional testing](https://github.com/Amsterdam/vergunningcheck/blob/master/TESTING.md)
- [ ] you added the necessary documentation (either in the markdown files or inline)
- [ ] you added the necessary automated tests

2021-01-04 09:05 UTC, afjlambert commented
@robinpiets Can you get this working locally? Let's discuss how to do the actual implementation.

2021-01-04 11:01 UTC, robinpiets requested changes
POC Works! I'm getting results from the db. Let's discuss implementation.

2021-01-04 11:01 UTC, robinpiets commented on packages/graphql/app.js
> +  password: process.env.DB_PASS,
This should be a more specific variable in case we get multiple database passwords. eg: `DB_PASS_DSR`, `DB_PASS_VEGETATION`, etc (after POC is finished)

2021-01-04 11:01 UTC, robinpiets commented on packages/graphql/app.js
> +  console.log(res.rows);
temp log (after POC is finished)

2021-01-08 09:09 UTC, afjlambert commented on packages/graphql/app.js
> +  password: process.env.DB_PASS,
What does DSR stand for?
Vegetation is maybe too narrow as we'll add more resources later.

Alternative could be `DSO_DB_PASS`?

2021-01-11 14:28 UTC, closed without merging