POC for pdf service
Amsterdam/vergunningcheck pull request #742
Opened 2020-12-17 11:37 UTC by afjlambert

Description 
- what does this feature or fix do?
- please explain (high level) how and why you implemented it this way

Please make sure:
- [ ] to add a label
- [ ] to add one or more reviewers
- [ ] you followed our checklist for [functional testing](https://github.com/Amsterdam/vergunningcheck/blob/master/TESTING.md)
- [ ] you added the necessary documentation (either in the markdown files or inline)
- [ ] you added the necessary automated tests

2021-01-04 09:04 UTC, afjlambert commented
@robinpiets Can you take a look at this? It's still in draft but feedback is welcome.

2021-01-04 10:49 UTC, robinpiets requested changes
Very nice POC. Got some feedback. Also, when running locally I downloaded a PDF with only the text "Loading"...

![image](https://user-images.githubusercontent.com/7781865/103527634-f484f000-4e82-11eb-805c-b18560fdde05.png)

2021-01-04 10:49 UTC, robinpiets commented on packages/client/src/utils/index.ts
> +  return;
If there's only one query variable there is no `&` but only a `?`, eg: `url/?var=value`. I think it's nice to add a fallback for this to make this function more general.

2021-01-04 10:49 UTC, robinpiets commented on packages/graphql/app.js
> +    "attachment; filename=indieningsvereisten.pdf"
Let's make the `filename` dynamic and required.

2021-01-04 10:49 UTC, robinpiets commented on packages/graphql/app.js
> +  }/vragen-en-uitkomst?data=${encodeURIComponent(req.query.data)}`;
Can we make the page `vragen-en-uitkomst` dynamic in case we change this. URI's have been changed frequently so maybe we can import this?

2021-01-04 10:49 UTC, robinpiets commented on packages/graphql/app.js
> +  const pdf = await page.pdf();
This is super nice!!! 🚀  Awesome find!

2021-01-04 10:49 UTC, robinpiets commented on packages/graphql/config/development.js
> +  pdfFrontend: "http://localhost:3000",
Ooooh. We need to make sure this is dynamic is well, because my dev server was running on port `3030`, so it didn't work initially (not required for this POC though)

2021-01-04 10:49 UTC, robinpiets commented on packages/client/src/components/PrintDetails.tsx
> +    {/* TODO: hide ?data=... from url */}
You can use `removeQueryStrings(window.location.href)` to remove everything after the `?` from a URI (import from `packages/client/src/utils/index.ts`)

2021-01-04 10:49 UTC, robinpiets commented on packages/client/src/components/Conclusion/ConclusionOutcome.tsx
> +        </p>
This needs to be `<Paragraph>` and `<Link>`, but I understand this is for testing purposes

2021-03-25 14:55 UTC, afjlambert commented
I'll close this PR as we will not soon implement this feature. I'll keep the branch around.

2021-03-25 14:56 UTC, closed without merging