New checkermodal redirect
Amsterdam/vergunningcheck pull request #811
Opened 2021-02-17 08:58 UTC by svenjens

Description 
This pr modified the flow from new checkmodal to intro text. 

Please make sure:
- [ ] to add a label
- [ ] to add one or more reviewers
- [ ] you followed our checklist for [functional testing](https://github.com/Amsterdam/vergunningcheck/blob/master/TESTING.md)
- [ ] you added the necessary documentation (either in the markdown files or inline)
- [ ] you added the necessary automated tests

2021-02-18 10:37 UTC, robinpiets commented on packages/client/src/components/Outcome/NewCheckerModal.tsx
> +      // Optionally save address
This comment is obsolete

2021-02-18 10:43 UTC, robinpiets commented on packages/client/src/components/Outcome/NewCheckerModal.tsx
> +    history.push(geturl(routes.intro, { slug: checkerSlug }));
Going to the intro page is only necessary when the checker is different from the current checker.

Current checkers should go either to the Location or Question Section. I will discuss today with UX and get back to you.

2021-02-18 10:48 UTC, robinpiets commented on packages/client/src/components/Location/LocationSection.tsx
> +  // useEffect(() => {
The part above (see `if (address) {`) is why the checker firesafety is broken when restarted. That should be a quick fix

2021-02-18 10:51 UTC, robinpiets commented on packages/client/src/components/Outcome/NewCheckerModal.tsx
> +      openButtonText={t("outcome.newCheckerModal.openModalBtnText")}
Nice translations!

2021-02-18 10:52 UTC, robinpiets requested changes
Nice draft. I've got some feedback to improve

2021-03-11 11:07 UTC, robinpiets commented on packages/client/src/components/Outcome/NewCheckerModal.tsx
> +        name: sections.INTRO,
This event is at the wrong place. Here should be an event  `ACTIVE_STEP` with `LOCATION_INPUT`

2021-03-11 11:09 UTC, robinpiets commented on packages/client/src/components/Outcome/NewCheckerModal.tsx
> +    setChecker(undefined);
For performance it might be better to place `setChecker(undefined)` underneath each `history.push`. Maybe you can test?

2021-03-11 13:26 UTC, robinpiets approved these changes
LGTM!

2021-03-15 15:22 UTC, robinpiets commented
I've updated the title and description to make them more precise.

2021-03-16 14:43 UTC, robinpiets commented
I've fixed the merge conflicts

2021-03-17 08:23 UTC, afjlambert approved these changes

2021-03-17 08:32 UTC, merged