Fixed modal height
Amsterdam/vergunningcheck pull request #863
Opened 2021-03-25 08:43 UTC by svenjens

Description 
This pr takes care of the modal, that it takes the width it needs. 

Please make sure:
- [ ] to add a label
- [ ] to add one or more reviewers
- [ ] you followed our checklist for [functional testing](https://github.com/Amsterdam/vergunningcheck/blob/master/TESTING.md)
- [ ] you added the necessary documentation (either in the markdown files or inline)
- [ ] you added the necessary automated tests

2021-03-25 09:05 UTC, robinpiets commented
It's not positioned correctly. you made it worse. Please follow our checklist for functional testing.

## your pr:
![image](https://user-images.githubusercontent.com/7781865/112447140-425a1780-8d51-11eb-96ac-d272876c19cf.png)
![image](https://user-images.githubusercontent.com/7781865/112447352-84835900-8d51-11eb-9535-c5fc53f946d4.png)
![image](https://user-images.githubusercontent.com/7781865/112447432-9bc24680-8d51-11eb-9802-7243151e1c28.png)


## production:
![image](https://user-images.githubusercontent.com/7781865/112447165-49812580-8d51-11eb-9398-f865a971c2bb.png)
![image](https://user-images.githubusercontent.com/7781865/112447311-79302d80-8d51-11eb-923d-6a97b41f76e2.png)

2021-03-25 09:06 UTC, robinpiets requested changes
Not fixed

2021-03-25 09:53 UTC, robinpiets commented
Please read the https://designsystem.amsterdam.nl/7awj1hc9f/p/59befd-popup

2021-04-12 14:12 UTC, afjlambert approved these changes

2021-05-06 12:10 UTC, merged